[package]
name = "integration-utils"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]

async-trait = "0.1.74"
anyhow = "1.0.75"
dotenv = "0.15.0"
near-units = "0.2"
futures = "0.3"
tokio = "1.28"
fake = "2.9"

near-workspaces = { workspace = true }
near-sdk = { workspace = true }
