[package]
name = "integration-utils"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
anyhow = "1.0.75"
dotenv = "0.15.0"
workspaces = "0.7.0"
near-units = "0.2.0"
futures = "0.3.28"
itertools = "0.11.0"
tokio = "1.33.0"
fake = "2.8.0"
