[package]
name = "integration-trait"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.36", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.67"

